src/Entity/Subscription.php
<?php

namespace App\Entity;

use App\Repository\SubscriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubscriptionRepository::class)]
class Subscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $fullName = null;

    #[ORM\Column(length: 255)]
    private ?string $UMPMail = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $homeLaboratory = null;

    #[ORM\Column(length: 255)]
    private ?string $homeInstitution = null;

    #[ORM\Column(length: 255)]
    private ?string $searchTheme = null;

    #[ORM\Column(length: 255)]
    private ?string $inscriptionYear = null;

    #[ORM\ManyToOne(inversedBy: 'subscriptions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?AnnonceFormation $annonceFormation = null;

    #[ORM\ManyToOne(inversedBy: 'userSubscriptions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $subscriber = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToMany(targetEntity: Atelier::class, inversedBy: 'subscriptions')]
    private Collection $ateliers;

    public function __construct()
    {
        $this->ateliers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getUMPMail(): ?string
    {
        return $this->UMPMail;
    }

    public function setUMPMail(string $UMPMail): self
    {
        $this->UMPMail = $UMPMail;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getHomeLaboratory(): ?string
    {
        return $this->homeLaboratory;
    }

    public function setHomeLaboratory(string $homeLaboratory): self
    {
        $this->homeLaboratory = $homeLaboratory;

        return $this;
    }

    public function getHomeInstitution(): ?string
    {
        return $this->homeInstitution;
    }

    public function setHomeInstitution(string $homeInstitution): self
    {
        $this->homeInstitution = $homeInstitution;

        return $this;
    }

    public function getSearchTheme(): ?string
    {
        return $this->searchTheme;
    }

    public function setSearchTheme(string $searchTheme): self
    {
        $this->searchTheme = $searchTheme;

        return $this;
    }

    public function getInscriptionYear(): ?string
    {
        return $this->inscriptionYear;
    }

    public function setInscriptionYear(string $inscriptionYear): self
    {
        $this->inscriptionYear = $inscriptionYear;

        return $this;
    }

    public function getAnnonceFormation(): ?AnnonceFormation
    {
        return $this->annonceFormation;
    }

    public function setAnnonceFormation(?AnnonceFormation $annonceFormation): self
    {
        $this->annonceFormation = $annonceFormation;

        return $this;
    }

    public function getSubscriber(): ?User
    {
        return $this->subscriber;
    }

    public function setSubscriber(?User $subscriber): self
    {
        $this->subscriber = $subscriber;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Atelier>
     */
    public function getAteliers(): Collection
    {
        return $this->ateliers;
    }

    public function addAtelier(Atelier $atelier): self
    {
        if (!$this->ateliers->contains($atelier)) {
            $this->ateliers->add($atelier);
        }

        return $this;
    }

    public function removeAtelier(Atelier $atelier): self
    {
        $this->ateliers->removeElement($atelier);

        return $this;
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\AnnonceFormation;
use App\Entity\Subscription;
use App\Entity\User;
use App\Form\AnnonceFormType;
use App\Form\SubscriptionFormType;
use App\Repository\AnnonceFormationRepository;
use App\Repository\SubscriptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Contracts\Cache\ItemInterface;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

#[Route('/formations/formation_doctorale')]
class FormationController extends AbstractController
{
    #[Route('/', name: 'app_formation_doctorale')]
    public function formation(): Response
    {
        if ($this->getUser() === null)
        {
            return $this->redirectToRoute("app_accueil");
        }

        return $this->render('web_site/formation.html.twig');
    }

    #[Route('/current_formation', name: 'app_formation_courante')]
    public function currentFormation(AnnonceFormationRepository $repository): Response
    {
        if ($this->getUser() === null)
        {
            return $this->redirectToRoute("app_accueil");
        }

        $current = $repository->findCurrentFormation();

        return $this->render('formation/currentFormation.html.twig', [
            'current'=>$current
        ]);
    }

    /**
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    #[Route('/inscription', name: "app_inscription")]
    public function inscriptionFormation(
        Request $request,
        EntityManagerInterface $manager,
        AnnonceFormationRepository $repository,
        SubscriptionRepository $subscriptionRepository
    ): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();

        /**
         * @var AnnonceFormation $activeFormation
         */
        $activeFormation = $repository->findCurrentFormation();

        /**
         * @var ?Subscription $subscription
         */
        $subscription = $subscriptionRepository->findOneBy(['subscriber'=>$user, 'annonceFormation'=>$activeFormation]);

        if ($subscription === null)
        {
            $subscription = new Subscription();

            $form = $this->createForm(SubscriptionFormType::class, $subscription);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid())
            {
                $subscription->setCreatedAt(new \DateTimeImmutable());
                $subscription->setSubscriber($user);
                $subscription->setAnnonceFormation($activeFormation);

                $manager->persist($subscription);
                $manager->flush();

                return $this->redirectToRoute("app_formation_doctorale");
            }

            return $this->render('formation/inscription.html.twig', [
                'subscription'=>$subscription,
                'form'=>$form->createView(),
                'activeFormation'=>$activeFormation,
            ]);

        } else {
            return $this->render('formation/inscription.html.twig', [
                'subscription'=>$subscription,
                'form'=>null
            ]);
        }

    }

    #[Route('/archives', name: "app_archives_formations")]
    public function archives(AnnonceFormationRepository $repository): Response
    {

        $oldFormations = $repository->findAllOldEditions();

        return $this->render('formation/archives.html.twig', [
            'formations'=>$oldFormations
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    #[Route('/résultats_d\'inscription', name: "app_results")]
    public function resultsFormation(CacheInterface $cache, ChartBuilderInterface $chartBuilder, SubscriptionRepository $repository, AnnonceFormationRepository $annonceFormationRepository): Response
    {
        /**
         * @var AnnonceFormation $activeFormation
         */
        $activeFormation = $annonceFormationRepository->findCurrentFormation();

        /**
         * @var AnnonceFormation $latestFormation
         */
        $latestFormation = $annonceFormationRepository->findOneBy([], ['droppedAt'=>'DESC']);

        /**
         * @var array<Subscription> $subscriptions
         */
        $subscriptions = $repository->findBy(['annonceFormation'=>$latestFormation], ['createdAt'=>'DESC']);
//        dd($subscriptions);

        /**
         * getting the institutions stats.
         */

        $valuesForInstitution = $cache->get('institution_cache', function (ItemInterface $item) use ($repository, $latestFormation) {
            $item->expiresAfter(3600);

            $arr = $repository->findInstitutions($latestFormation);

            $institutions = [];
            $counts = [];

            foreach ($arr as $elm)
            {
                $institutions[] = $elm['homeInstitution'];
                $counts[] = $elm['count'];
            }

            return ['institutions' => $institutions, 'counts' => $counts];
        });

        /**
         * getting the ateliers stats.
         */

//        $cache->delete('atelier_cache');
        $valuesForAtelier = $cache->get('atelier_cache', function (ItemInterface $item) use ($repository, $latestFormation) {
            $item->expiresAfter(3600);

            $arr = $repository->findAteliers($latestFormation);

            $labels = [];
            $counts = [];

            foreach ($arr as $elm)
            {
                $labels[] = $elm['name'];
                $counts[] = $elm['count'];
            }

            return ['labels' => $labels, 'counts' => $counts];
        });

        /**
         * getting the years stats.
         */

        $valuesForYears = $cache->get('years_cache', function (ItemInterface $item) use ($repository, $latestFormation) {
            $item->expiresAfter(3600);

            $arr = $repository->findYears($latestFormation);

            $years = [];
            $counts = [];

            foreach ($arr as $elm)
            {
                $years[] = $elm['year'];
                $counts[] = $elm['count'];
            }

            return ['years' => $years, 'counts' => $counts];
        });

        /**
         * Charts...
         */

        $chartForInstitution = $chartBuilder->createChart(Chart::TYPE_BAR);
        $chartForInstitution->setData([
            'labels'=>$valuesForInstitution['institutions'],
            'datasets'=>[
                [
                    'backgroundColor' => [
                        'rgb(255, 185, 49)',
                        'rgb(103, 74, 64)',
                        'rgb(156, 195, 154)',
                        'rgb(204, 221, 239)',
                        'rgb(160, 123, 230)',
                    ],
                    'borderColor' => 'rgb(0, 0, 0)',
                    'data' => $valuesForInstitution['counts'],
                    'axis'=>'y',
                    'borderWidth'=>2
                ]
            ]
        ]);
        $chartForInstitution->setOptions([
            'indexAxis'=>'y',
            'plugins'=> [
                'legend'=>[
                    'display'=> false
                ]
            ]
        ]);

        /*--------------------------------------------------------------------------------*/

        $chartForYear = $chartBuilder->createChart(Chart::TYPE_PIE);
        $chartForYear->setData([
            'labels'=>$valuesForYears['years'],
            'datasets'=>[
                [
                    'backgroundColor' => [
                        'rgb(255, 185, 49)',
                        'rgb(103, 74, 64)',
                        'rgb(156, 195, 154)',
                        'rgb(204, 221, 239)',
                        'rgb(160, 123, 230)',
                        'rgb(111, 29, 87)'
                    ],
                    'borderColor' => 'rgb(0, 0, 0)',
                    'data' => $valuesForYears['counts'],
                ]
            ]
        ]);

        $chartForYear->setOptions([
            'plugins'=> [
                'legend'=>[
                    'display'=> true
                ]
            ]
        ]);

        /*--------------------------------------------------------------------------------*/

//        $chartForLabos = $chartBuilder->createChart(Chart::TYPE_BAR);
//        $chartForLabos->setData([
//            'labels'=>[
//                'Communication éducation linguistique et Humanités numériques',
//                'GRET',
//                'Interdisciplinaire de Recherche Economiques, Économétriques et Managériales',
//                'LARGAIM',
//                'LERITEDA',
//                'LIRAM',
//                'LURIGOR',
//                'LURICOR',
//                'MARSAG ENCGT',
//                'MADEO',
//                'Économie sociale et solidaire et développement local',
//            ],
//            'datasets'=>[
//                [
//                    'backgroundColor' => [
//                        'rgb(255, 185, 49)'
//                    ],
//                    'borderColor' => 'rgb(0, 0, 0)',
//                    'data' => [15, 10, 5, 2, 20, 30, 12, 6, 5, 18, 7],
//                ]
//            ]
//        ]);
//        $chartForLabos->setOptions([
//            'indexAxis'=>'y',
//            'plugins'=> [
//                'legend'=>[
//                    'display'=> false
//                ]
//            ]
//        ]);

        /*--------------------------------------------------------------------------------*/

templates/formation/archives.html.twig
{% extends 'base.html.twig' %}

{% block title %}Archive des formations{% endblock %}

{% block main %}

    <main class="main mt-40">

        {% for formation in formations %}

            <div class="m-5 flex flex-col justify-center items-center shadow-3xl dark:bg-white/5 rounded-xl m-7 p-7">
                <div class="text-3xl font-bold" >{{ formation.title }}</div>
                <div>
                    <img src="{{ asset('uploads/cards/' ~ formation.card ) }}" alt="{{ "formation" ~ formation.id }}">
                </div>
                <div class="shadow-inner bg-black/5 dark:bg-white/5 rounded-xl w-full p-5 mt-5 mb-5">{{ formation.description }}</div>
                <div>
                    <div>Annoncée le <span class="font-bold text-xl text-green-500">{{ formation.dateDebut | date('d/m/Y') }}</span> à <span class="font-bold text-xl text-green-500">{{ formation.dateDebut | date('H:i') }}</span></div>
                </div>
            </div>

            <hr>

        {% endfor %}

    </main>

{% endblock %}

templates/formation/currentFormation.html.twig
{% extends 'base.html.twig' %}

{% block title %}OnBoarding-Doctoring{% endblock %}

{% block main %}

    <main class="main mt-40">

        {% if current %}
            <div class="m-5 flex flex-col justify-center items-center shadow-3xl dark:bg-white/5 rounded-xl m-7 p-7">
                <div class="text-3xl font-bold" >{{ current.title }}</div>
                <div>
                    <img src="{{ asset('uploads/cards/' ~ current.card ) }}" alt="courante">
                </div>
                <div class="shadow-inner bg-black/5 dark:bg-white/5 rounded-xl w-full p-5 mt-5 mb-5">{{ current.description }}</div>
                <div class="flex flex-row space-x-52">
                    <div>
                        <div>Annoncée le <span class="font-bold text-xl text-green-500">{{ current.dateDebut | date('d/m/Y') }}</span> à <span class="font-bold text-xl text-green-500">{{ current.dateDebut | date('H:i') }}</span></div>
                        <div>Dernier delai des inscriptions <span class="font-bold text-xl text-red-500">{{ current.dateFin | date('d/m/Y') }}</span> à <span class="font-bold text-xl text-red-500">{{ current.dateFin | date('H:i') }}</span></div>
                    </div>
                    {% if 'ROLE_ADMIN' in app.user.roles %}
                        <div class="flex flex-row">
                            <a href="{{ path("app_edit_current_formation", {"slug": current.slug}) }}">
                                <button class="text-primary flex flex-row justify-center items-center bg-green-400 rounded-xl hover:bg-green-500/95 w-[75px] h-12 mr-5">
                                    <img src="{{ asset('images/edit-file.png') }}" alt="edit" class="w-7 h-7">
                                </button>
                            </a>
                            <a href="{{ path("app_delete_current_formation", {"slug" : current.slug}) }}">
                                <button class="text-primary flex flex-row justify-center items-center bg-red-400 rounded-xl hover:bg-red-500/95 w-[75px] h-12 mr-5">
                                    <img src="{{ asset('images/delete-file.png') }}" alt="delete" class="w-7 h-7">
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>

            <a href="{{ path('app_inscription') }}">
                <div class="mb-5 shadow-3xl rounded-xl hover:bg-primary hover:text-secondary dark:bg-white/5 dark:hover:text-black dark:hover:bg-secondary hover:transition-all hover:ease-in-out hover:duration-500 w-44 h-16 relative top-7 left-1/2 -translate-y-1/2 -translate-x-1/2">
                    <div class="flex flex-row items-center text-center justify-center pt-1.5">Inscrivez-vous maintenant!!</div>
                </div>
            </a>
        {% else %}
            <div class="relative m-5 w-1/2 small:p-5 relative small:top-24 left-1/2 small:-translate-y-1/4 translate-y-1/4 -translate-x-1/2 h-80 small:h-64 shadow-3xl rounded-xl dark:border-2 dark:border-blue-600 flex flex-col justify-evenly items-center">
                <p class="text-xl text-center small:text-xs font-bold hover:text-blue-600">Pas de formation pour le moment...</p>
                <img src="{{ asset('images/no-task.png') }}" alt="Vide Pour le moment" class="w-16 h-16 small:w-10 small:h-10 absolute -top-5 -right-7 small:-right-2 small:-top-5 -rotate-45">
                <img src="{{ asset('images/hour-glass.png') }}" alt="en attente" class="w-20 h-20 small:w-16 small:h-16 animate-rotation relative">
            </div>

            <div class="h-7 mt-7"></div>
        {% endif %}

    </main>

{% endblock %}

templates/formation/inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription...{% endblock %}

{% block main %}

    <main class="main mt-40">

        {% if not form %}

            <div class="m-5 w-1/2 small:p-5 relative small:top-24 left-1/2 small:-translate-y-1/4 translate-y-1/4 -translate-x-1/2 h-80 small:h-64 shadow-3xl rounded-xl dark:border-2 dark:border-green-500 flex flex-col justify-evenly items-center">
                <img src="{{ asset('images/double-check.png') }}" alt="ok" class="w-16 h-16 small:w-10 small:h-10 absolute -top-7 -right-7 small:-right-2 small:-top-5 rotate-12">
                <p class="text-xl text-center small:text-xs font-bold hover:text-green-500">Vous êtes déjà inscrit dans la formation</p>
                <img src="{{ asset('images/valide.png') }}" alt="déjaInscrit" class="w-32 h-32 small:w-16 small:h-16 animate-bounce relative">
            </div>

            <div class="h-7 mt-7"></div>
        {% else%}

            <p class="text-center my-9 small:my-5 md:font-bold small:text-sm">Inscrivez-vous et embarquez à bord du Onboarding doctoring !</p>
            <div class="m-5 h-full">

                {{ form_start(form, {
                    'attr': {
                        'class': 'ml-16 mr-16 shadow-3xl dark:border-2 dark:border-secondary rounded-xl h-full small:ml-0.5 small:mr-0.5'
                    }
                }) }}
                <div class="p-5 flex flex-col justify-between">
                    <label class="text-xl text-blue-700 dark:text-secondary">Nom et Prénom</label>
                    {{ form_widget(form.fullName , {
                        'attr': {
                            'placeholder': 'Nom complet',
                            'class': 'mb-10 bg-black/5 justify-between p-5 focus:outline-none shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Adresse e-mail institutionnel</label>
                    {{ form_widget(form.UMPMail , {
                        'attr': {
                            'placeholder': 'adresse mail...',
                            'class': 'mb-10 bg-black/5 justify-between p-5 focus:outline-none shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Numéro de téléphone</label>
                    {{ form_widget(form.phone , {
                        'attr': {
                            'class': 'mb-10 bg-black/5 justify-between p-5 focus:outline-none shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Laboratoire  d'attache</label>
                    {{ form_widget(form.homeLaboratory , {
                        'attr': {
                            'class': 'mb-10 bg-black/5 justify-between p-5 focus:outline-none shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Etablissement d'attache relevant du Pôle thématique Droit, Economie et gestion de l'Université Mohammed Premier</label>
                    {{ form_widget(form.homeInstitution , {
                        'attr': {
                            'class': 'mb-10 bg-black/5 justify-between p-5 shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Thème de recherche</label>
                    {{ form_widget(form.searchTheme , {
                        'attr': {
                            'class': 'mb-10 bg-black/5 justify-between p-5 focus:outline-none shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Année d'inscription au cycle doctoral</label>
                    {{ form_widget(form.inscriptionYear , {
                        'attr': {
                            'class': 'mb-10 bg-black/5 justify-between p-5 shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}
                    <label class="text-xl text-blue-700 dark:text-secondary">Ateliers de formation : Vous pouvez vous inscrire à autant d'ateliers que vous voulez</label>
                    {{ form_widget(form.ateliers , {
                        'attr': {
                            'class': 'mb-10 bg-black/5 justify-between p-5 shadow-inner rounded-xl dark:border-2 dark:border-secondary w-full'
                        }
                    }) }}

                    <button type="submit" class="mt-3 text-primary font-bold bg-secondary rounded-xl hover:bg-[#D19900] w-[95px] h-10">Envoyer</button>

                </div>
                {{ form_end(form) }}
            </div>
        {% endif %}

    </main>

{% endblock %}

templates/formation/results.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultats des inscriptions{% endblock %}

{% block main %}

    <main class="main mt-40 small:mt-32">

        <div class="m-7 flex flex-col justify-between space-y-7">
            <div id="count" class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary">
                <div>
                    <p class="text-xl font-bold">{{ subscriptions | length }} Réponses</p>
                </div>
                <div>
                    <p>
                        {% if activeFormation %}
                            La période d'inscription est <span class="text-green-500 font-bold">Ouverte.</span>
                        {% else %}
                            La période d'inscription est <span class="text-purple-500 font-bold">Clôturée.</span>
                        {% endif %}
                    </p>
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="names">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Nom et prénom</div>
                <div id="scroll-div" class="overflow-hidden overflow-y-scroll h-52">
                    <div id="scroll-content" class="mr-5">
                        {% for subscription in subscriptions %}
                            <p class="bg-black/5 dark:bg-white/30 p-1.5 my-1 rounded-md">{{ subscription.fullName }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="addresses">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Adresse e-mail institutionnel</div>
                <div id="scroll-div" class="overflow-hidden overflow-y-scroll h-52">
                    <div id="scroll-content" class="mr-5">
                        {% for subscription in subscriptions %}
                            <p class="bg-black/5 dark:bg-white/30 p-1.5 my-1 rounded-md">{{ subscription.uMPMail }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="phones">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Numéro de téléphone</div>
                <div id="scroll-div" class="overflow-hidden overflow-y-scroll h-52">
                    <div id="scroll-content" class="mr-5">
                        {% for subscription in subscriptions %}
                            <p class="bg-black/5 dark:bg-white/30 p-1.5 my-1 rounded-md">{{ subscription.phone }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="labos">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Laboratoire  d'attache</div>
                <div id="scroll-div" class="overflow-hidden overflow-y-scroll h-52">
                    <div id="scroll-content" class="mr-5">
                        {% for subscription in subscriptions %}
                            <p class="bg-black/5 dark:bg-white/30 p-1.5 my-1 rounded-md">{{ subscription.homeLaboratory }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="universities">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Etablissement d'attache relevant du Pôle thématique Droit, Economie et gestion de l'Université Mohammed Premier</div>
                <div>
                    {{ render_chart(chartForInstitution) }}
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="themes">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Thème de recherche</div>
                <div id="scroll-div" class="overflow-hidden overflow-y-scroll h-52">
                    <div id="scroll-content" class="mr-5">
                        {% for subscription in subscriptions %}
                            <p class="bg-black/5 dark:bg-white/30 p-1.5 my-1 rounded-md">{{ subscription.searchTheme }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="year">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Année d'inscription au cycle doctoral</div>
                <div>
                    {{ render_chart(chartForYear) }}
                </div>
            </div>
            <div class="shadow-3xl rounded-xl p-5 dark:border-2 dark:border-secondary" id="ateliers">
                <div class="font-bold text-lg bg-black/10 dark:bg-secondary dark:text-black rounded-md p-2.5 my-3">Ateliers de formation</div>
                <div>
                    {{ render_chart(chartForAteliers) }}
                </div>
            </div>
        </div>

    </main>

{% endblock %}